-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'REJECTED');

-- AlterTable
ALTER TABLE "User" ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'PENDING_APPROVAL';
ALTER TABLE "User" ADD COLUMN "requestedDepartment" VARCHAR(200);
ALTER TABLE "User" ADD COLUMN "requestedRole" VARCHAR(64);
ALTER TABLE "User" ADD COLUMN "requestReason" TEXT;
ALTER TABLE "User" ADD COLUMN "approvedBy" UUID;
ALTER TABLE "User" ADD COLUMN "approvedAt" TIMESTAMPTZ(6);
ALTER TABLE "User" ADD COLUMN "rejectedBy" UUID;
ALTER TABLE "User" ADD COLUMN "rejectedAt" TIMESTAMPTZ(6);
ALTER TABLE "User" ADD COLUMN "rejectionReason" TEXT;
